### ISSUE TITLE
Local installations // Animations Fail

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/visualize-change#66] opened 2018-07-09 04:10 UTC
The animations created, saved and shared to my own email no longer work. Initially they did, but now they appear to be timing out towards the end.

A png snap shot of each time frame is taken, before they are stitched together for an mp4 or gif. However the process times out before all the snap shots are taken, for example at png 21/30 the process stalls and then restarts itself from the beginning.

Will try to re-install the tool locally with newer code although it shouldn't have been affected since it initially worked. Perhaps the .env settings I have no longer are valid as these were provided by @szymonkaliski

**Comment by szymonkaliski** [comment] 2018-07-26 10:51
Closing this as it's duplicate of #70

**Closed by szymonkaliski** 2018-07-26 10:51 UTC
Labels: Bug
